### ISSUE TITLE
Share listing on macOS (High) Sierra

### ISSUE THREAD

**Issue by mcd2000** [rapid7/smbj-rpc#129]
I'm trying to write an SMB2 client for Android. I need to read share list from the server. I'm doing something like this:

```
SmbConfig cfg = SmbConfig.builder().
                        withMultiProtocolNegotiate(true).
                        withSecurityProvider(new BCSecurityProvider()).
                        build();
SMBClient client = new SMBClient(cfg);

try (Connection connection = client.connect("server")) {
   AuthenticationContext ac = new AuthenticationContext(username, password.toCharArray(), "WORKGROUP");
   Session session = connection.authenticate(ac);

   RPCTransport transport = SMBTransportFactories.SRVSVC.getTransport(session);
   final ServerService serverService = new ServerService(transport);
   final List<NetShareInfo0> shares = serverService.getShares0();
   for (final NetShareInfo0 share : shares) {
     System.out.println(share);
   }
 } catch (Exception e) {
 }
         
```           
This code works fine when connected to Windows 10 PC, but I'am constantly getting the following exception with both macOS Sierra (10.12.8) and High Sierra (10.13.3) at "getTransport" method:                
com.rapid7.helper.smbj.io.SMB2Exception:
SMB2_CREATE returned STATUS_ACCESS_DENIED (3221225506/3221225506): expected=[STATUS_SUCCESS]

Is it anything I just do not understand here?

**Comment by hschottm** [comment]
This must have to do with Apples SMBx implementation. smbj-RPC is throwing an exception when it tries to create a named pipe by sending and SMB2 create request. The response is an "Access denied" which then causes the exception.

Any workaround to this issue would be very helpful.

**Comment by fiasko131** [comment]
Same issue here with 10.5.9 LEOPARD

Any ideas?

Thanks

**Comment by imbokhary** [comment]
I'm also facing the same issue with MAC OS only.
`try{
            final Connection smbConnection = smbClient.connect(mAddress);
            final AuthenticationContext smbAuthenticationContext = new AuthenticationContext(
                    String.valueOf(userName),
                    passWord,
                    String.valueOf(domain));
            final Session session = smbConnection.authenticate(smbAuthenticationContext);

            final RPCTransport transport = SMBTransportFactories.SRVSVC.getTransport(session);
            final ServerService serverService = new ServerService(transport);
            final List<NetShareInfo0> shares = serverService.getShares0();

            for (final NetShareInfo0 share : shares) {
                shareNameList.add(share.getNetName().toString());
                Log.d(TAG, share.getNetName().toString());
            }
        }catch(Exception e) {
            e.printStackTrace();
        }`

W/System.err: com.rapid7.helper.smbj.io.SMB2Exception: SMB2_CREATE returned 3221225506 (3221225506/3221225506): expected=[STATUS_SUCCESS]
W/System.err:     at com.rapid7.helper.smbj.io.SMB2SessionMessage.sendAndRead(SMB2SessionMessage.java:99)
W/System.err:     at com.rapid7.helper.smbj.share.NamedPipe.<init>(NamedPipe.java:56)
W/System.err:     at com.rapid7.client.dcerpc.transport.SMBTransportFactories.openPipe(SMBTransportFactories.java:99)
W/System.err:     at com.rapid7.client.dcerpc.transport.SMBTransportFactories.openAndHandleStatusPipeNotAvailable(SMBTransportFactories.java:74)
W/System.err:     at com.rapid7.client.dcerpc.transport.SMBTransportFactories.getTransport(SMBTransportFactories.java:58)
W/System.err:     at com.samsung.android.app.networkstoragemanager.rpc.SMBjRPC.getShareList(SMBjRPC.java:49)


is there any solution ??

**Comment by imbokhary** [comment]
@tosmun-r7 
hello, I've fixed the issue on smbj-rpc related to share listing for MAC and I've tested it on MAC, Windows and Linux too working well. Changes should be pushed.

**Comment by mcd2000** [comment]
@imbokhary Could, please, at least share the patch?

**Comment by Hhcoco** [comment]
@imbokhary 
Any ideas?

Thanks

**Comment by ppdgithub** [comment]
Any update on this issue ?

**Comment by mreiterer** [comment]
Any update on this issue ?

**Comment by dkocher** [comment]
@imbokhary It would be great if you can share your fix.

**Comment by chrisgch** [comment]
I recently encountered the same problem when connecting to the latest MacOS Sequoia 15.6. My tests with SMB2 and Wireshark (on Windows) lead me to the solution. There are 2 changes needed to smbj-rpc:

1. In file com\rapid7\helper\smbj\share\NamedPipe.java, in the constructor, the function SMB2CreateRequest is called with parameter EnumSet.of(AccessMask.MAXIMUM_ALLOWED). MacOS isn't understanding MAXIMUM_ALLOWED and returns an error. Windows does not use MAXIMUM_ALLOWED to open IPC$. Instead it passes the individual rights it needs to the server. To match this behaviour, change the parameter to:
EnumSet.of(AccessMask.FILE_READ_DATA,AccessMask.FILE_WRITE_DATA,AccessMask.FILE_APPEND_DATA,
                        AccessMask.FILE_READ_EA,AccessMask.FILE_WRITE_EA,
                        AccessMask.FILE_READ_ATTRIBUTES,AccessMask.FILE_WRITE_ATTRIBUTES,
                        AccessMask.READ_CONTROL,AccessMask.SYNCHRONIZE)

Now the bind call to IPC$ succeeds, but the call to NetShareEnumAll still fails and requires a small change:
2. In file com\rapid7\client\dcerpc\mssrvs\messages\NetrShareEnumRequest.java function marshal, a preferred maximum length of is sent:
packetOut.writeInt(this.preferredMaximumLength);
I need to change this to 0xFFFFFFFF (-1) which means MAX_PREFERRED_LENGTH to make it work with MacOS.

**Comment by kuangchen2025** [comment]
> I recently encountered the same problem when connecting to the latest MacOS Sequoia 15.6. My tests with SMB2 and Wireshark (on Windows) lead me to the solution. There are 2 changes needed to smbj-rpc:
> 
> 1. In file com\rapid7\helper\smbj\share\NamedPipe.java, in the constructor, the function SMB2CreateRequest is called with parameter EnumSet.of(AccessMask.MAXIMUM_ALLOWED). MacOS isn't understanding MAXIMUM_ALLOWED and returns an error. Windows does not use MAXIMUM_ALLOWED to open IPC$. Instead it passes the individual rights it needs to the server. To match this behaviour, change the parameter to:
>    EnumSet.of(AccessMask.FILE_READ_DATA,AccessMask.FILE_WRITE_DATA,AccessMask.FILE_APPEND_DATA,
>    AccessMask.FILE_READ_EA,AccessMask.FILE_WRITE_EA,
>    AccessMask.FILE_READ_ATTRIBUTES,AccessMask.FILE_WRITE_ATTRIBUTES,
>    AccessMask.READ_CONTROL,AccessMask.SYNCHRONIZE)
>    According to Microsoft documentation, "Access mode" must be set to "Allow read and write operations".
>    Therefore the correct parameter to pass would be just EnumSet.of(AccessMask.FILE_READ_DATA,AccessMask.FILE_WRITE_DATA)
>    https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/4b0b077a-46f0-40a6-ad13-b5488d3720d0
> 
> Now the bind call to IPC$ succeeds, but the call to NetShareEnumAll still fails and requires a small change:
> 
> 2. In file com\rapid7\client\dcerpc\mssrvs\messages\NetrShareEnumRequest.java function marshal, a preferred maximum length of is sent:packetOut.writeInt(this.preferredMaximumLength);
>    I need to change this to 0xFFFFFFFF (-1) which means MAX_PREFERRED_LENGTH to make it work with MacOS.

Thanks @chrisgch , it works for me!

**Comment by DepthCoreTech** [comment]
In addition to the two modifications @chrisgch mentioned, another parameter 'createDisposition' of the 'SMB2CreateRequest' class constructor also needs to be changed from 'SMB2CreateDisposition.FILE_OPEN_IF' to 'SMB2CreateDisposition.FILE_OPEN'. 
In fact, as long as this parameter does not include '*_IF', it can be accepted by macOS.

**Comment by chrisgch** [comment]
You are right, I had changed it previously to SMB2CreateDisposition.FILE_OPEN too.
