### ISSUE TITLE
I have support it for smbj 0.11.1

### ISSUE THREAD

**Issue by DaveBoy** [rapid7/smbj-rpc#158]
i hope it can help others

it works well  in my project

[DaveBoy/smbj-rpc](https://github.com/DaveBoy/smbj-rpc)

**Comment by vaidehisadhu** [comment]
Thanks for this @DaveBoy.
I merged your changes and I get the following error (Not sure if this is some share-related issues or if there is something that I am missing. Would appreciate help with this) :

Exception in thread "main" com.rapid7.helper.smbj.io.SMB2Exception: SMB2_IOCTL returned 3221225485 (3221225485/3221225485): expected=[STATUS_SUCCESS, STATUS_BUFFER_OVERFLOW]
	at com.rapid7.helper.smbj.io.SMB2SessionMessage.sendAndRead(SMB2SessionMessage.java:100)
	at com.rapid7.helper.smbj.share.NamedPipe._ioctl(NamedPipe.java:110)
	at com.rapid7.helper.smbj.share.NamedPipe.transact(NamedPipe.java:66)
	at com.rapid7.client.dcerpc.transport.SMBTransport.transact(SMBTransport.java:33)
	at com.rapid7.client.dcerpc.transport.RPCTransport.bind(RPCTransport.java:54)
	at com.rapid7.client.dcerpc.transport.SMBTransportFactories.getTransport(SMBTransportFactories.java:62)
	at main.java.smbjupgrade.BasicEvaluation.getSecurityDescriptor(BasicEvaluation.java:246)
	at main.java.smbjupgrade.BasicEvaluation.main(BasicEvaluation.java:541)
	
	
Line 246 in my code is RPCTransport rpcTransport = SMBTransportFactories.LSASVC.getTransport(session, config);

The code works perfectly fine when I undo these changes and use smbj-0.10.0

**Comment by DaveBoy** [comment]
> Thanks for this @DaveBoy.
> I merged your changes and I get the following error (Not sure if this is some share-related issues or if there is something that I am missing. Would appreciate help with this) :
> 
> Exception in thread "main" com.rapid7.helper.smbj.io.SMB2Exception: SMB2_IOCTL returned 3221225485 (3221225485/3221225485): expected=[STATUS_SUCCESS, STATUS_BUFFER_OVERFLOW]
> at com.rapid7.helper.smbj.io.SMB2SessionMessage.sendAndRead(SMB2SessionMessage.java:100)
> at com.rapid7.helper.smbj.share.NamedPipe._ioctl(NamedPipe.java:110)
> at com.rapid7.helper.smbj.share.NamedPipe.transact(NamedPipe.java:66)
> at com.rapid7.client.dcerpc.transport.SMBTransport.transact(SMBTransport.java:33)
> at com.rapid7.client.dcerpc.transport.RPCTransport.bind(RPCTransport.java:54)
> at com.rapid7.client.dcerpc.transport.SMBTransportFactories.getTransport(SMBTransportFactories.java:62)
> at main.java.smbjupgrade.BasicEvaluation.getSecurityDescriptor(BasicEvaluation.java:246)
> at main.java.smbjupgrade.BasicEvaluation.main(BasicEvaluation.java:541)
> 
> Line 246 in my code is RPCTransport rpcTransport = SMBTransportFactories.LSASVC.getTransport(session, config);
> 
> The code works perfectly fine when connected with SMB2Dialect.SMB_2_1, SMB2Dialect.SMB_3_0 and SMB2Dialect.SMB_3_0_2. But gives the above error with SMB2Dialect.SMB_3_1_1.

i'm sorry for that i am not good at support more,i just edit some places  for  new method change.

**Comment by asmith-r7** [comment]
> Thanks for this @DaveBoy.
> I merged your changes and I get the following error (Not sure if this is some share-related issues or if there is something that I am missing. Would appreciate help with this) :
> 
> Exception in thread "main" com.rapid7.helper.smbj.io.SMB2Exception: SMB2_IOCTL returned 3221225485 (3221225485/3221225485): expected=[STATUS_SUCCESS, STATUS_BUFFER_OVERFLOW]
> at com.rapid7.helper.smbj.io.SMB2SessionMessage.sendAndRead(SMB2SessionMessage.java:100)
> at com.rapid7.helper.smbj.share.NamedPipe._ioctl(NamedPipe.java:110)
> at com.rapid7.helper.smbj.share.NamedPipe.transact(NamedPipe.java:66)
> at com.rapid7.client.dcerpc.transport.SMBTransport.transact(SMBTransport.java:33)
> at com.rapid7.client.dcerpc.transport.RPCTransport.bind(RPCTransport.java:54)
> at com.rapid7.client.dcerpc.transport.SMBTransportFactories.getTransport(SMBTransportFactories.java:62)
> at main.java.smbjupgrade.BasicEvaluation.getSecurityDescriptor(BasicEvaluation.java:246)
> at main.java.smbjupgrade.BasicEvaluation.main(BasicEvaluation.java:541)
> 
> Line 246 in my code is RPCTransport rpcTransport = SMBTransportFactories.LSASVC.getTransport(session, config);
> 
> The code works perfectly fine when connected with SMB2Dialect.SMB_2_1, SMB2Dialect.SMB_3_0 and SMB2Dialect.SMB_3_0_2. But gives the above error with SMB2Dialect.SMB_3_1_1.

Can you try and reproduce on the development branch I just pushed? Then we can narrow down if this is an issue with this project or SMBJ.

**Comment by DaveBoy** [comment]
> Thanks for this @DaveBoy. I merged your changes and I get the following error (Not sure if this is some share-related issues or if there is something that I am missing. Would appreciate help with this) :
> 
> Exception in thread "main" com.rapid7.helper.smbj.io.SMB2Exception: SMB2_IOCTL returned 3221225485 (3221225485/3221225485): expected=[STATUS_SUCCESS, STATUS_BUFFER_OVERFLOW] at com.rapid7.helper.smbj.io.SMB2SessionMessage.sendAndRead(SMB2SessionMessage.java:100) at com.rapid7.helper.smbj.share.NamedPipe._ioctl(NamedPipe.java:110) at com.rapid7.helper.smbj.share.NamedPipe.transact(NamedPipe.java:66) at com.rapid7.client.dcerpc.transport.SMBTransport.transact(SMBTransport.java:33) at com.rapid7.client.dcerpc.transport.RPCTransport.bind(RPCTransport.java:54) at com.rapid7.client.dcerpc.transport.SMBTransportFactories.getTransport(SMBTransportFactories.java:62) at main.java.smbjupgrade.BasicEvaluation.getSecurityDescriptor(BasicEvaluation.java:246) at main.java.smbjupgrade.BasicEvaluation.main(BasicEvaluation.java:541)
> 
> Line 246 in my code is RPCTransport rpcTransport = SMBTransportFactories.LSASVC.getTransport(session, config);
> 
> The code works perfectly fine when connected with SMB2Dialect.SMB_2_1, SMB2Dialect.SMB_3_0 and SMB2Dialect.SMB_3_0_2. But gives the above error with SMB2Dialect.SMB_3_1_1.

this error happen in my version and in the rapid7's version(0.12.0),it seems just happen on the win11
#164
